'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Leaflet from 'leaflet';
import official from '@/data/public-evidence.json';
export default function RoadMap({filter,placeId,radius,onPlace}:{filter:string;placeId:string|null;radius:number;onPlace:(id:string)=>void}){
 const container=useRef<HTMLDivElement>(null),map=useRef<Leaflet.Map|null>(null),layer=useRef<Leaflet.LayerGroup|null>(null),[ready,setReady]=useState(false),[tilesFailed,setTilesFailed]=useState(false);
 const callback=useRef(onPlace);callback.current=onPlace;
 useEffect(()=>{let disposed=false;import('leaflet').then(L=>{if(disposed||!container.current)return;const m=L.map(container.current,{zoomControl:false,scrollWheelZoom:false}).setView([52.205,0.125],13);map.current=m;L.control.zoom({position:'bottomleft'}).addTo(m);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>setTilesFailed(true)).addTo(m);layer.current=L.layerGroup().addTo(m);const resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(container.current);m.on('unload',()=>resize.disconnect());setReady(true);});return()=>{disposed=true;map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!ready)return;let disposed=false;import('leaflet').then(L=>{if(disposed||!map.current||!layer.current)return;const g=layer.current;g.clearLayers();for(const p of official.map_points){if(filter==='cyclist'&&!p.cyclist_count||filter==='pedestrian'&&!p.pedestrian_count)continue;const label=document.createElement('div');label.textContent=`${p.date} · ${p.casualty_count} injured people · national final`;L.circleMarker([p.latitude,p.longitude],{radius:p.severity===2?5:3,color:'#153c51',weight:1,fillColor:'#26aabd',fillOpacity:0.65}).bindPopup(label).addTo(g);}
 for(const p of official.places){const selected=p.place_id===placeId;L.circleMarker([p.latitude,p.longitude],{radius:selected?11:7,fillColor:selected?'#f5b652':'#faf8f2',color:'#102532',weight:3,fillOpacity:1}).bindTooltip(p.display_name).on('click',()=>callback.current(p.place_id)).addTo(g);if(selected){L.circle([p.latitude,p.longitude],{radius,color:'#bc730e',weight:2,fillColor:'#f5b652',fillOpacity:0.13}).addTo(g);map.current.setView([p.latitude,p.longitude],16);}}
 if(!placeId)map.current.setView([52.205,0.125],13);});return()=>{disposed=true;};},[ready,filter,placeId,radius]);
 return <div className="map-wrap"><div ref={container} className="map" aria-label="Cambridge map of official injury collisions and selected junction"/>{tilesFailed&&<div className="tile-warning">Street tiles unavailable. Evidence points and records remain available.</div>}<div className="map-key"><span className="key-point"/> National injury collisions <span className="key-junction"/> Junction context</div><a className="map-issue" href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noreferrer">Report a map issue</a></div>;
}
