'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,AudioLines,MapPin,Radio,ShieldCheck,ChevronRight,Search,RefreshCw,Check,LoaderCircle,ChevronDown,Layers} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Badge} from '@/components/ui/badge';
import RoadMap from './roadlens-map';
import EvaluationResults from './evaluation-results';
import official from '@/data/public-evidence.json';
import type {AnalysisResult} from '@/contracts/generated';
type Report={report_id:string;category:string;place_id:string;junction:string;received_at:string;analysis_status:string;review_status:string;source:string};
type Detail={report:{observation:string};intake_run:any;analysis:AnalysisResult|null;error:string|null};
const issueNames:Record<string,string>={visibility_obstruction:'Visibility concern',road_surface:'Road surface',crossing_concern:'Crossing concern',access_obstruction:'Access obstruction',speeding_concern:'Speeding concern',signal_or_lighting:'Signal or lighting',other_road_concern:'Road concern'};
const limitations:Record<string,string>={no_causal_evidence:'These records do not establish what caused the collision.',no_exposure_denominator:'Traffic and pedestrian exposure are not supplied; these counts cannot rank which junction is safest.',current_imagery_not_supplied:'Current imagery not supplied. Present crossing markings and visibility have not been assessed.',overlapping_sources:'The national and local sources overlap. Their totals must be shown separately, never added.',historic_conditions:'Recorded road categories describe the date of the collision, not conditions today.',unverified_resident_observation:'The resident concern is an independent observation awaiting officer review.'};
const checks:Record<string,string>={check_current_sightlines:'Check current sightlines around parked vehicles.',observe_crossing_access:'Observe crossing access and pedestrian movements.',check_surface_condition:'Inspect the present road surface.',check_signal_or_lighting:'Check the signal or lighting on site.',measure_speeds_and_exposure:'Measure speeds and traffic exposure before comparing risk.',verify_location_on_site:'Verify the approximate junction reference point on site.'};
const when=(s:string)=>new Date(s).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
async function api(path:string,options?:RequestInit){const r=await fetch('/api/'+path,{cache:'no-store',...options});const b:any=await r.json();if(!r.ok)throw Error(b.error??'Request unavailable');return b;}
function Fact({m}:{m:any}){return <div className="answer-fact"><strong>{m.value}</strong><div><b>{m.unit}</b><span>{m.query.road_user!=='all'?m.query.road_user+'s · ':''}{m.period_start} — {m.period_end}</span><span>{m.geography} · {m.provisional?'Local provisional':'National final'}</span><a href={official.sources.find(s=>s.source_id===m.source_id)?.url} target="_blank" rel="noreferrer">Source and provenance <ArrowUpRight size={12}/></a></div></div>;}
function Answer({result}:{result:AnalysisResult}){const output=result.output;if(output.kind==='needs_clarification')return <p>{output.question}</p>;return <div className="answer">{result.evidence.metrics.filter(m=>output.metric_refs.includes(m.reference_id)).map(m=><Fact key={m.reference_id} m={m}/>)}{output.limitations.map(k=><p className="limitation" key={k}>{limitations[k]}</p>)}{output.inspection_checks.length>0&&<div className="inspection"><b>Suggested inspection checks</b>{output.inspection_checks.map(k=><p key={k}><Check size={15}/>{checks[k]}</p>)}</div>}</div>;}
function Run({run}:{run:any}){return <details className="run"><summary><Layers size={15}/> Evidence & run <ChevronDown size={15}/></summary><p className="mono">{run.run_id}</p><p>{run.model} · {Number(run.elapsed_seconds).toFixed(1)}s</p>{run.classifier&&<p>GLiNER · {run.classifier.issue_label}<br/><span className="muted">{run.classifier.model} · {run.classifier.revision.slice(0,12)}</span></p>}<p>{run.tools.length} tool events · {run.validation_repairs.length} validation repairs</p>{run.tools.map((e:any,i:number)=><details key={i}><summary>{e.name}</summary><pre>{JSON.stringify({inputs:e.inputs,output:e.output},null,2)}</pre></details>)}{run.validation_repairs.map((x:string,i:number)=><p key={i}>{x}</p>)}<details><summary>Snapshot and prompt hashes</summary><pre>{JSON.stringify({data:run.data_hashes,prompt:run.prompt_hash,commit:run.code_commit},null,2)}</pre></details></details>;}
export default function Dashboard(){
 const [reports,setReports]=useState<Report[]>([]),[selected,setSelected]=useState<string|null>(null),[place,setPlace]=useState<string|null>(null),[filter,setFilter]=useState('all'),[radius,setRadius]=useState(100),[detail,setDetail]=useState<Detail|null>(null),[isOwner,setOwner]=useState(false),[signedIn,setSignedIn]=useState(false),[connection,setConnection]=useState('Connecting'),[error,setError]=useState(''),[question,setQuestion]=useState(''),[answer,setAnswer]=useState<AnalysisResult|null>(null),[busy,setBusy]=useState(false),[jobState,setJobState]=useState(''),[tab,setTab]=useState('context');
 const cursor=useRef(0);const chosen=reports.find(r=>r.report_id===selected);const alive=useRef(true);
 useEffect(()=>{alive.current=true;let stopped=false,timer:ReturnType<typeof setTimeout>;api('identity').then(v=>{if(!stopped){setOwner(v.owner);setSignedIn(v.signed_in);}}).catch(()=>{});const poll=async()=>{try{const data=await api('public/reports?after='+cursor.current);if(stopped)return;cursor.current=data.cursor;setReports(old=>{const values=new Map(old.map(r=>[r.report_id,r]));data.reports.forEach((r:Report)=>values.set(r.report_id,r));return [...values.values()].sort((a,b)=>b.received_at.localeCompare(a.received_at));});setConnection('Live feed');}catch{if(!stopped)setConnection('Reconnecting');}if(!stopped)timer=setTimeout(poll,2000);};poll();return()=>{stopped=true;alive.current=false;clearTimeout(timer);};},[]);
 useEffect(()=>{let stopped=false;setDetail(null);if(selected&&isOwner)api('officer/reports/'+selected).then(x=>{if(!stopped)setDetail(x);}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;};},[selected,isOwner,chosen?.analysis_status,chosen?.review_status]);
 const context=official.local_context.find(p=>p.location.place_id===place&&p.radius_metres===radius);const location=official.places.find(p=>p.place_id===place);
 const nearby=context?.records;
 async function ask(text=question){if(!text.trim()||busy)return;setBusy(true);setError('');setAnswer(null);setJobState('Queued');setTab('assistant');try{const j=await api('officer/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:text,report_id:selected})});for(let i=0;i<100&&alive.current;i++){await new Promise(r=>setTimeout(r,2000));const x=await api('officer/jobs/'+j.job_id);setJobState(x.state==='running'?'Checking official evidence':x.state);if(x.state==='failed')throw Error('Analysis unavailable. Your reports remain saved.');if(x.result){setAnswer(x.result);const metric=x.result.evidence.metrics[0];if(metric){setFilter(metric.query.road_user);if(!metric.query.place_id)setPlace(null);else setPlace(metric.query.place_id);}break;}}}catch(e){setError(e instanceof Error?e.message:'Analysis unavailable');}finally{if(alive.current)setBusy(false);}}
 function pick(r:Report){setSelected(r.report_id);setPlace(r.place_id);setTab('context');setError('');}
 async function action(op:string,payload:object){if(!selected)return;try{await api('officer/reports/'+selected+'/'+op,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});cursor.current=0;}catch(e){setError(e instanceof Error?e.message:'Unavailable');}}
 return <div className="app-shell"><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><AudioLines size={24}/></span>Road<span>Lens</span></a><div className="top-title">Cambridge · Road safety desk</div><div className="top-actions"><span className="feed-indicator"><Radio size={15}/>{connection}</span>{isOwner?<span className="officer-label"><ShieldCheck size={16}/> Officer workspace</span>:<a className="signin" href="/signin-with-chatgpt?return_to=%2F" target="_top">{signedIn?'Owner access required':'Officer sign in'}<ArrowUpRight size={14}/></a>}</div></header>
 <main><section className="scope"><div><MapPin size={16}/><b>Cambridge district</b><span>E07000008</span></div><div><span>Evidence period</span><b>Jan — Dec 2025</b><Badge className="final-badge">National final</Badge></div></section>
 <section className="metrics" aria-label="National final 2025 statistics">{[{value:official.metrics[0].value,label:'People injured',sub:'Casualty records',filter:'all'},{value:official.metrics[2].value,label:'Cyclists injured',sub:'People, not collisions',filter:'cyclist'},{value:official.metrics[3].value,label:'Pedestrians injured',sub:'People, not collisions',filter:'pedestrian'},{value:official.metrics[1].value,label:'Injury collisions',sub:'Distinct collision records',filter:'all'}].map((m,i)=><button key={m.label} className={'metric '+(filter===m.filter&&i<3?'active':'')} onClick={()=>{setFilter(m.filter);setPlace(null);}}><span>{m.label}</span><strong>{m.value}<ArrowUpRight size={22}/></strong><small>{m.sub}</small></button>)}</section>
 <div className="workspace"><section className="map-panel"><div className="panel-heading"><h2>Evidence map</h2><span>{filter==='all'?'All road users':filter==='cyclist'?'Cyclists':'Pedestrians'}</span><Button variant="ghost" size="sm" onClick={()=>{setPlace(null);setFilter('all');}}>Reset view</Button></div><RoadMap filter={filter} placeId={place} radius={radius} onPlace={id=>{setPlace(id);setSelected(null);}}/><div className="map-footer"><b>{location?location.display_name:'Cambridge, England'}</b><span>{location?'Approximate historic reference point':'Police-reported injury collisions · 2025'}</span></div></section>
 <section className="inbox-panel"><div className="panel-heading"><h2>Resident reports</h2><span className="count">{reports.length}</span></div><div className="inbox-scroll">{reports.length===0?<div className="empty-inbox"><AudioLines size={32}/><h3>Ready to listen</h3><p>Confirmed reports from the voice box appear here.</p><span>Microphone controlled by the resident</span></div>:reports.map(r=><button className={'report-card '+(selected===r.report_id?'selected':'')} key={r.report_id} onClick={()=>pick(r)}><div><span className="report-source"><AudioLines size={14}/> Voice report</span><time>{when(r.received_at)}</time></div><h3>{issueNames[r.category]??'Road concern'}</h3><p>{r.junction}</p><span className={'status '+r.analysis_status}>{r.analysis_status==='complete'?'Evidence ready':r.analysis_status==='failed'?'Analysis unavailable':r.analysis_status==='running'?'Checking evidence':'Received · queued'}</span><small>{r.review_status==='awaiting_officer_review'?'Awaiting officer review':r.review_status==='reviewed'?'Reviewed by officer':'Archived'}</small><ChevronRight className="report-arrow" size={17}/></button>)}</div><div className="inbox-foot"><ShieldCheck size={15}/> Only confirmed reports are saved.</div></section>
 <section className="evidence-panel"><Tabs value={tab} onValueChange={setTab}><TabsList className="evidence-tabs"><TabsTrigger value="context">Case evidence</TabsTrigger><TabsTrigger value="assistant">Officer assistant</TabsTrigger></TabsList><TabsContent value="context" className="evidence-scroll">{chosen?<><div className="eyebrow">Resident voice report</div><h2>{issueNames[chosen.category]}</h2><p className="location-title">{chosen.junction}</p><Badge variant="outline">{chosen.review_status.replaceAll('_',' ')}</Badge>{detail&&<blockquote>“{detail.report.observation}”<cite>Resident observation · unverified</cite></blockquote>}{isOwner&&chosen.review_status==='awaiting_officer_review'&&<Button variant="outline" onClick={()=>action('review',{status:'reviewed'})}><Check size={15}/> Mark reviewed</Button>}{isOwner&&chosen.analysis_status==='failed'&&<Button variant="outline" onClick={()=>action('retry',{})}><RefreshCw size={15}/> Retry analysis</Button>}</>:<><div className="eyebrow">Official context</div><h2>{location?'Junction evidence':'A clearer view of the road'}</h2><p className="muted">Select a resident report or explore a junction to see dated evidence.</p>{!place&&<Button className="explore" variant="outline" onClick={()=>setPlace('vicarage-st-matthews')}><MapPin size={16}/> Vicarage Terrace / St Matthews Street</Button>}</>}
 {context&&<><div className="context-heading"><h3>{location?.display_name}</h3><label>Search radius <select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={50}>50 m</option><option value={100}>100 m</option><option value={250}>250 m</option></select></label></div><p className="period-note">Local snapshot · Jan 2017–Jun 2026<br/>Search radius, not an exact junction boundary.</p>{nearby?.map(r=><article className="collision" key={r.reference_id}><div><b>{new Date(r.date).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</b>{r.provisional&&<Badge className="provisional">Provisional</Badge>}</div><p><strong>{r.casualty_count}</strong> injured {r.casualty_count===1?'person':'people'} · {r.severity.toLowerCase()} collision</p><small>Record {r.collision_id} · casualty severities not inferred</small><details><summary>Historic recorded categories</summary><p>{r.junction_detail}</p><p>{r.crossing}</p><p>These categories describe {r.date}; they do not establish conditions today.</p></details></article>)}</>}
 {detail?.analysis&&<><Answer result={detail.analysis}/><Run run={detail.analysis.run}/></>}{detail?.intake_run&&<Run run={detail.intake_run}/>}<div className="imagery-note">Current imagery not supplied</div><p className="provenance-note">Historical records provide context. They do not establish the cause of a resident’s concern.</p><div className="source-links">{official.sources.map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.source_id}>{s.title}<ArrowUpRight size={13}/></a>)}</div></TabsContent>
 <TabsContent value="assistant" className="evidence-scroll"><div className="eyebrow">Ask the evidence</div><h2>From concern to inspection</h2><p className="muted">Answers use dated source records. Review decisions remain yours.</p>{isOwner?<><div className="suggestions"><button onClick={()=>ask('Show cyclists injured in Cambridge in 2025.')}>Show cyclists injured in 2025 <ArrowUpRight size={14}/></button><button onClick={()=>ask('Did parked cars cause collision 1737997?')}>Did parked cars cause that collision? <ArrowUpRight size={14}/></button></div><form onSubmit={e=>{e.preventDefault();ask();}}><label htmlFor="question">Question for RoadLens</label><div className="question-row"><Input id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about Cambridge road evidence…" maxLength={2000}/><Button type="submit" disabled={busy||!question.trim()} aria-label="Ask RoadLens"><Search size={18}/></Button></div></form>{busy&&<div className="thinking" role="status"><LoaderCircle size={18} className="spin"/>{jobState}</div>}{answer&&<><Answer result={answer}/><Run run={answer.run}/></>}</>:<div className="signin-card"><ShieldCheck size={25}/><p>Officer questions and private report details are available to the site owner.</p><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT <ArrowUpRight size={15}/></a></div>}</TabsContent></Tabs>{error&&<div className="error" role="alert">{error}</div>}</section></div><EvaluationResults/><footer className="footer"><span>ROADLENS <span className="footer-sep">/</span> Resident observation → Dated evidence → Human review</span><span>National final and local provisional counts remain separate.</span></footer></main></div>;
}
