"""Generate runtime Zod validators and inferred TS types from Pydantic JSON Schema."""
import json
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from backend import models
ROOT = Path(__file__).resolve().parents[1]
def zod(s, defs):
    if isinstance(s,bool):return 'z.unknown()' if s else 'z.never()'
    if '$ref' in s: return zod(defs[s['$ref'].split('/')[-1]], defs)
    if 'const' in s: return 'z.literal('+json.dumps(s['const'])+')'
    if 'enum' in s:
        if all(isinstance(x,str) for x in s['enum']):return 'z.enum('+json.dumps(s['enum'])+' as const)'
        return 'z.union(['+','.join('z.literal('+json.dumps(x)+')' for x in s['enum'])+'])'
    if 'anyOf' in s or 'oneOf' in s: return 'z.union(['+','.join(zod(x,defs) for x in s.get('anyOf',s.get('oneOf')))+'])'
    t=s.get('type')
    if t=='null': return 'z.null()'
    if t=='boolean': return 'z.boolean()'
    if t in ['number','integer']:
        x='z.number()'+('.int()' if t=='integer' else '')
        for k,method in [('minimum','min'),('maximum','max')]:
            if k in s:x+=f'.{method}({s[k]})'
        return x
    if t=='string':
        x='z.string()'
        for k,method in [('minLength','min'),('maxLength','max')]:
            if k in s:x+=f'.{method}({s[k]})'
        if 'pattern' in s:x+='.regex(new RegExp('+json.dumps(s['pattern'])+'))'
        if s.get('format')=='date-time':x+='.datetime({offset:true})'
        if s.get('format')=='date':x+='.regex(/^\\d{4}-\\d{2}-\\d{2}$/)'
        return x
    if t=='array':
        x='z.array('+zod(s['items'],defs)+')'
        for k,method in [('minItems','min'),('maxItems','max')]:
            if k in s:x+=f'.{method}({s[k]})'
        return x
    if t=='object':
        if 'properties' not in s:return 'z.record('+zod(s.get('additionalProperties',{}) or {},defs)+')'
        props=[]
        for k,v in s['properties'].items():
            x=zod(v,defs)
            if 'default' in v:x+='.default('+json.dumps(v['default'])+')'
            elif k not in s.get('required',[]):
                x+='.default([])' if v.get('type')=='array' else '.optional()'
            props.append(json.dumps(k)+':'+x)
        return 'z.object({'+','.join(props)+'})'+('.strict()' if s.get('additionalProperties') is False else '')
    return 'z.unknown()'
names=['PrepareRequest','ReadyDraft','NeedsClarification','OutOfScope','Submission','IntakeResponse','AnalysisResult','OfficerQuestion','JobResult']
out=['// Generated by scripts/export-contracts.py. Do not edit.','import { z } from "zod";'];schemas={}
for name in names:
    schema=getattr(models,name).model_json_schema();schemas[name]=schema
    out += [f'export const {name}Schema = '+zod(schema,schema.get('$defs',{}))+';',f'export type {name} = z.infer<typeof {name}Schema>;']
(ROOT/'contracts/generated.ts').write_text('\n'.join(out)+'\n')
(ROOT/'contracts/schema.json').write_text(json.dumps(schemas,indent=2)+'\n')
from backend.evidence import Repository
(ROOT/'data/public-evidence.json').write_text(json.dumps(Repository().public_evidence(),separators=(',',':'))+'\n')
